//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentRent.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int ID { get; set; }
        public int ClientEquipmentID { get; set; }
        public System.DateTime RentStart { get; set; }
        public System.DateTime RentEnd { get; set; }
        public System.DateTime ReturnTime { get; set; }
    
        public virtual ClientEquipment ClientEquipment { get; set; }
    }
}
